/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package computersystemsecurity;

import java.awt.Container;
import java.awt.Image;
import java.awt.Taskbar;
import java.awt.Toolkit;
import java.net.URL;

import javax.swing.JButton;
import javax.swing.JFrame;

public class App extends JFrame{
    Container container;
    JButton AesFileEncryptionPanelButton, HashAndDigitalSignaturePanelButton, RSAKeyPairGeneratorPanelButton,
            SymmetricKeyEncryptionPanelButton;
    public static void main(String[] args) {
        new App();
    }

    public App() {
        super("Computer System Security");
        final Toolkit defaultToolkit = Toolkit.getDefaultToolkit();
        final URL imageResource = App.class.getClassLoader().getResource("icon.png");
        final Image image = defaultToolkit.getImage(imageResource);

        final Taskbar taskbar = Taskbar.getTaskbar();

        try {
            //set icon for mac os (and other systems which do support this method)
            taskbar.setIconImage(image);
        } catch (final UnsupportedOperationException e) {
            System.out.println("The os does not support: 'taskbar.setIconImage'");
        } catch (final SecurityException e) {
            System.out.println("There was a security exception for: 'taskbar.setIconImage'");
        }

        this.setIconImage(image);

        Initialize();
    }

    public void Initialize() {
        CreateComponents();
        AddContainer();
        SetBounds();
        AddActionListeners();


        
        this.setSize(400, 330);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        this.setResizable(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public void CreateComponents() {
        container = getContentPane();
        container.setLayout(null);
        AesFileEncryptionPanelButton = new JButton("AES File Encryption");
        HashAndDigitalSignaturePanelButton = new JButton("Hash and Digital Signature");
        RSAKeyPairGeneratorPanelButton = new JButton("RSA Key Pair Generator");
        SymmetricKeyEncryptionPanelButton = new JButton("Symmetric Key Encryption");
    }
    public void AddContainer() {
        container.add(AesFileEncryptionPanelButton);
        container.add(HashAndDigitalSignaturePanelButton);
        container.add(RSAKeyPairGeneratorPanelButton);
        container.add(SymmetricKeyEncryptionPanelButton);
    }
    public void SetBounds() {
        AesFileEncryptionPanelButton.setBounds(50, 20, 300, 50);
        HashAndDigitalSignaturePanelButton.setBounds(50, 90, 300, 50);
        RSAKeyPairGeneratorPanelButton.setBounds(50, 160, 300, 50);
        SymmetricKeyEncryptionPanelButton.setBounds(50, 230, 300, 50);
    }

    public void AddActionListeners() {
        AesFileEncryptionPanelButton.addActionListener(e -> {
            new AESFileEncryption();
            this.dispose();
        });
        HashAndDigitalSignaturePanelButton.addActionListener(e -> {
            new HashAndDigitalSignature();
            this.dispose();
        });
        RSAKeyPairGeneratorPanelButton.addActionListener(e -> {
            new RSAKeyPairGenerator();
            this.dispose();
        });
        SymmetricKeyEncryptionPanelButton.addActionListener(e -> {
            new SymmetricKeyEncryption();
            this.dispose();
        });
    }

    public Object getGreeting() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getGreeting'");
    }
}
